{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Instance Property","title":"url","symbolKind":"property","modules":[{"name":"StytchCore"}],"externalID":"s:10StytchCore0A8APIErrorC3url10Foundation3URLVSgvp"},"abstract":[{"type":"text","text":"The url at which further information about the error can be found. Nil if no additional information available."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/stytch-ios.StytchCore\/documentation\/StytchCore\/StytchAPIError\/url"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stytchcore\/stytchapierror\/url"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/stytch-ios.StytchCore\/documentation\/StytchCore","doc:\/\/stytch-ios.StytchCore\/documentation\/StytchCore\/StytchAPIError"]]},"references":{"doc://stytch-ios.StytchCore/documentation/StytchCore/StytchAPIError/url":{"role":"symbol","abstract":[{"type":"text","text":"The url at which further information about the error can be found. Nil if no additional information available."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?","kind":"text"}],"title":"url","type":"topic","identifier":"doc:\/\/stytch-ios.StytchCore\/documentation\/StytchCore\/StytchAPIError\/url","url":"\/documentation\/stytchcore\/stytchapierror\/url","kind":"symbol"},"doc://stytch-ios.StytchCore/documentation/StytchCore":{"role":"collection","identifier":"doc:\/\/stytch-ios.StytchCore\/documentation\/StytchCore","abstract":[{"type":"text","text":"Provides native iOS access to the Stytch SDK methods for ultimate flexibility."}],"kind":"symbol","type":"topic","title":"StytchCore","url":"\/documentation\/stytchcore"},"doc://stytch-ios.StytchCore/documentation/StytchCore/StytchAPIError":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StytchAPIError"}],"navigatorTitle":[{"kind":"identifier","text":"StytchAPIError"}],"title":"StytchAPIError","type":"topic","identifier":"doc:\/\/stytch-ios.StytchCore\/documentation\/StytchCore\/StytchAPIError","abstract":[{"text":"Error class representing an error within the Stytch API.","type":"text"}],"kind":"symbol","url":"\/documentation\/stytchcore\/stytchapierror"}}}